name: Build and test

on:
  push:
    branches:
      - main
      - develop
      - feature_*

  pull_request:
    branches:
      - main
      - develop
      - feature_*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Prepare
        run: |
          sudo apt install lcov libsofthsm2 libsystemd-dev -y
          pip install conan

      - name: Build and test
        run: |
          mkdir build

          conan profile detect --force

          conan install ./conan/ --output-folder build --settings=build_type=Debug --build=missing
          cmake ./ -B./build/ -DCMAKE_TOOLCHAIN_FILE=./conan_toolchain.cmake \
            -DWITH_TEST=ON -DWITH_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug

          cd build
          make; make tests; make coverage

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: build/Testing/Temporary/LastTest.log
          if-no-files-found: ignore

      - name: Upload codecov report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage.total
